# Generated by Django 5.2 on 2025-05-09 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_reel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='audio_name',
        ),
        migrations.AlterField(
            model_name='reel',
            name='caption',
            field=models.TextField(default='No caption'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=models.FileField(upload_to='reels/'),
        ),
    ]
