# Generated by Django 5.2 on 2025-05-09 15:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_reel_audio_name_alter_reel_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
