# Generated by Django 5.2 on 2025-05-15 06:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
