# Generated by Django 5.1.7 on 2025-04-20 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_shared_with_alter_post_shared_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_with_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='shared_by',
            field=models.ManyToManyField(blank=True, related_name='shared_by_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
