# Generated by Django 5.2 on 2025-05-15 07:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio')),
                ('movie_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='filter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
