# Generated by Django 5.2 on 2025-05-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_audiotrack_post_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.audiotrack'),
        ),
    ]
