# Generated by Django 5.2 on 2025-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotrack',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration of audio in seconds', null=True),
        ),
    ]
