# Generated by Django 5.1.7 on 2025-04-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_notification_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
    ]
