# Generated by Django 5.2 on 2025-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_audiotrack_movie_name_audiotrack_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='file',
            field=models.FileField(upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
