# Generated by Django 5.2 on 2025-05-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_audiotrack_duration_alter_audiotrack_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='post',
            name='filter',
        ),
        migrations.DeleteModel(
            name='AudioTrack',
        ),
    ]
