# Generated by Django 5.2 on 2025-05-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_audio_remove_post_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filter',
            field=models.CharField(blank=True, default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
