# Generated by Django 5.2 on 2025-04-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_image_alter_post_video_alter_story_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
