# Generated by Django 5.2 on 2025-04-28 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_image_alter_post_video_alter_story_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='story_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
