# Generated by Django 5.2 on 2025-05-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filter',
            field=models.CharField(choices=[('none', 'Normal'), ('grayscale(100%)', 'Grayscale'), ('sepia(100%)', 'Sepia'), ('blur(5px)', 'Blur'), ('contrast(200%)', 'High Contrast')], default='none', max_length=50),
        ),
    ]
