# Generated by Django 5.2 on 2025-05-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_comment_post'),
        ('users', '0016_customuser_is_private_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.followrequest'),
        ),
    ]
