# Generated by Django 5.1.7 on 2025-03-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
