# Generated by Django 5.1.7 on 2025-04-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/default-profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
