# Generated by Django 5.1.7 on 2025-04-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
