# Generated by Django 5.2 on 2025-04-26 02:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_pics/default-profile.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
