# Generated by Django 5.2 on 2025-05-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(blank=True, default='profile_pics/default-profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
