# Generated by Django 5.2 on 2025-05-22 11:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_is_private_followrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='default-profile_cymv7l', max_length=255, null=True, verbose_name='image'),
        ),
    ]
