from django.urls import path
from .views import (
    PostListView, PostCreateView, PostDetailView, 
    PostUpdateView, PostDeleteView, like_post, 
    save_post, add_comment, delete_comment,
    dashboard, send_story_message, inbox, share_post,notifications_view,story_list_view
)
from . import views
urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('like/<int:post_id>/', like_post, name="like-post"),
    path('save/<int:post_id>/', save_post, name="save-post"),
    path('comments/<int:comment_id>/delete/', delete_comment, name="comment-delete"),
    path('posts/<int:post_id>/comment/', add_comment, name="add-comment"),
    path('dashboard/', dashboard, name='dashboard'),
    path('inbox/', inbox, name='inbox'),
    path('share/<int:post_id>/', views.share_post, name='share-post'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('notifications/', notifications_view, name='notifications'),
    path('posts/story_upload/', views.upload_story, name='story-upload'),
    path('stories/<int:story_id>/', views.story_detail_view, name='story-detail'),
    path('posts/<int:story_id>/share/', views.share_story, name='share-story'),
    path('story/<int:story_id>/delete/', views.delete_story, name='delete-story'),
    path('stories/', story_list_view, name='story-list'),
    path('stories/my/', views.my_story_view, name='my-story'), 
    path('story/<int:story_id>/like/', views.like_story, name='like-story'),
    path('send-story-message/<str:username>/', send_story_message, name='send-story-message'),
    path('send/<int:receiver_id>/', views.send_message, name='send-message'),
    path('mention-suggestions/', views.mention_suggestions, name='mention-suggestions'),
    path('chat/<str:username>/', views.chat_view, name='chat'),
    path('reels/', views.reel_list, name='reel-list'),
    path('reels/<int:reel_id>/like/', views.like_reel, name='like-reel'),
    path('share-reel/', views.share_reel, name='share-reel'),
    path('reels/<int:reel_id>/comments/', views.reel_comments, name='reel_comments'),
    path('comments/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    path('comment/<int:comment_id>/reply/', views.reply_to_comment, name='reply_to_comment'),
    path('reels/<int:reel_id>/save/', views.save_reel, name='save_reel'),
    path('reels/<int:reel_id>/report/', views.report_reel, name='report-reel'),
    path('reports/', views.view_reports, name='view-reports'),
    path('unsave/', views.unsave_post, name='unsave-post'),
    path('saved/', views.saved_content, name='saved'),  
    path('saved-posts/', views.saved_posts_view, name='saved-posts'),
    path('saved-reels/', views.saved_reels_view, name='saved-reels'),


]
